repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      additional_dependencies: ["flake8-builtins", "pep8-naming"]